### ISSUE TITLE
Position of axis labels are affected

### ISSUE THREAD

**Issue by chinmayeelm** [kakearney/offsetaxis-pkg#2]
This package does exactly what I wanted. Only issue is that my figure labels are clipped after the offset. 
![memPot_processing_axisoffset](https://github.com/kakearney/offsetaxis-pkg/assets/25946537/a8d990e0-a8ad-4da1-aa1c-02244df88ca4)

What can I do to fix this. I do not want change the figure size. I don't mind the plot getting smaller. 
I tried to put the outerposition constraint. It still doesn't work.

**Comment by kakearney** [comment]
If you don't mind the plot getting smaller, I suggest resizing your axes before adding the offset axis.  You might have to play around with the width to see what works for your purposes.  Here's a quick example:

```Matlab
figure;
hax(1) = subplot(2,1,1);
hax(2) = subplot(2,1,2);

ylabel(hax(1), {'This ylabel', 'gets very wide'}, 'rotation', 0);
offsetaxis(hax(1));

set(hax(2), 'Position', hax(2).Position + [0.2 0 -0.2 0]); % <- shrinks the axis width by 0.2
ylabel(hax(2), {'This ylabel', 'gets very wide'}, 'rotation', 0);
offsetaxis(hax(2));
```
![offsetaxis_issue2](https://github.com/kakearney/offsetaxis-pkg/assets/5015092/e804fc4f-047d-4dd9-be44-976dcce46c21)

The behavior you noticed (i.e. that the axis doesn't automatically resize to make room for the y-label) occurs because the new axes are manually positioned relative to the original ones.  As soon as you manually set position-related properties, Matlab turns off any auto-resizing behavior.  In the context of this function, it would be very difficult to maintain any sort of auto-resizing behavior while also allowing the user to create offset axes with the flexible properties available here. So I leave it to the user to make sure the original axis is formatted such that it allows space for any new offsets.
